name: teste_gdm
description: "Teste técnico GDM"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  http: ^1.3.0
  provider: ^6.1.2
  toggle_switch: ^2.3.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11  
  mocktail: ^1.0.4
  modular_test: ^2.0.0

flutter:
  assets:
    - .env
  uses-material-design: true